#DataPilot AI

## Intelligent Data Analyst Agent

### Author
Robert Chonge

---

## Project Description

DataPilot AI is an intelligent data analyst capable of:

- Uploading CSV/Excel datasets
- Cleaning messy data
- Performing automated exploratory data analysis (EDA)
- Generating business insights
- Creating interactive dashboards
- Answering natural language questions about data
- Recommending machine learning models
- Producing downloadable reports

---

## Technologies

- Python
- Pandas
- NumPy
- Plotly
- Gradio
- Scikit-Learn
- LangChain
- DuckDB
- YData Profiling
- Matplotlib

---

## Dataset

Sales Analytics Dataset

---

## Development Environment

Google Colab

---

## Deployment

- Hugging Face Spaces
- GitHub

---

Let's build an AI Data Analyst.

DEPENDENCIES

In [ ]:

# ==========================================
# INSTALL DEPENDENCIES
# ==========================================

!pip install -q \
gradio \
plotly \
openpyxl \
xlrd \
ydata-profiling \
duckdb \
langchain \
langchain-community \
sentence-transformers \
faiss-cpu \
scikit-learn \
matplotlib \
seaborn \
kaleido \
tabulate \
missingno

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.8/400.8 kB 8.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 23.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 48.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.5/18.5 MB 78.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.6/55.6 kB 4.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.6/52.6 kB 4.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 54.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 94.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.7/679.7 kB 42.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 5.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 8.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 6.2 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.

# 📚 Importing Libraries

This section imports every library required throughout the project.

The notebook is organised so imports appear only once.

In [ ]:
# ==========================================
# IMPORTS
# ==========================================

import os
import warnings
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

import gradio as gr

from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer

from ydata_profiling import ProfileReport

warnings.filterwarnings("ignore")

/tmp/ipykernel_2465/1783532521.py:20: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

# 📂 Mount Google Drive

The dataset is stored in Google Drive.

Google Drive acts as permanent storage while Colab provides the compute environment.

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
DATASET_PATH = "/content/drive/MyDrive/datapilot_sample_sales_analytics.csv"

# 🔍 Verify Dataset

Before loading the dataset,we ensure the file exists.

In [ ]:
import os

if os.path.exists(DATASET_PATH):
    print("✅ Dataset found!")
    print(DATASET_PATH)
else:
    print("❌ Dataset not found.")

✅ Dataset found!
/content/drive/MyDrive/datapilot_sample_sales_analytics.csv

# 📥 Load Dataset

DataPilot AI automatically supports

- CSV
- Excel (.xlsx)

In [ ]:
def load_dataset(path):

    extension = path.split(".")[-1].lower()

    if extension == "csv":
        df = pd.read_csv(path)

    elif extension in ["xlsx", "xls"]:
        df = pd.read_excel(path)

    else:
        raise ValueError("Unsupported file format.")

    return df

In [ ]:
df = load_dataset(DATASET_PATH)

# 👀 Preview Dataset

Let's inspect the first few records.

In [ ]:
df.head()

,Transaction_ID,Date,Customer_ID,Customer_Segment,Region,Country,Product_Category,Product_Name,Quantity,Unit_Price,Discount_Rate,Total_Sales,Net_Profit,Payment_Method,CSAT_Score,Churn_Risk
0,TXN-10001,2025-01-01,CUST-0239,SMB,Latin America,Brazil,Cloud Services,Serverless Compute Pack,2,430.18,0.00,860.36,507.61,PayPal,5.0,Low
1,TXN-10002,2025-01-01,CUST-0212,Enterprise,North America,USA,Consulting Services,Data Pipeline Audit,14,1566.40,0.25,16447.20,8223.60,Direct Debit,2.0,Medium
2,TXN-10003,2025-01-01,CUST-0212,SMB,Asia Pacific,Japan,Software,Cloud Sync Suite,3,194.03,0.10,523.88,199.07,Credit Card,1.0,Medium
3,TXN-10004,2025-01-02,CUST-0168,Consumer,North America,USA,Cloud Services,Serverless Compute Pack,2,435.67,0.05,827.77,438.72,Direct Debit,3.0,Medium
4,TXN-10005,2025-01-02,CUST-0123,SMB,Europe,Germany,Hardware & Hardware Accessories,IoT Gateway Hub,3,355.95,0.05,1014.46,618.82,PayPal,4.0,Low

# 📊 Dataset Dimensions

Understanding the size of the dataset.

In [ ]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 1003
Columns: 16

# 📝 Column Information

Display

- Column names
- Data types
- Missing values

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1003 entries, 0 to 1002
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    1003 non-null   object
 1   Date              1003 non-null   object
 2   Customer_ID       1003 non-null   object
 3   Customer_Segment  1003 non-null   object
 4   Region            1003 non-null   object
 5   Country           1003 non-null   object
 6   Product_Category  1003 non-null   object
 7   Product_Name      1003 non-null   object
 8   Quantity          1003 non-null   int64
 9   Unit_Price        1003 non-null   float64
 10  Discount_Rate     1003 non-null   float64
 11  Total_Sales       1003 non-null   float64
 12  Net_Profit        1003 non-null   float64
 13  Payment_Method    1003 non-null   object
 14  CSAT_Score        945 non-null    float64
 15  Churn_Risk        1003 non-null   object
dtypes: float64(5), int64(1), object(10)
memory usage: 125.5+ KB

# 🔎 Display Column Names

In [ ]:
for col in df.columns:
    print(col)

Transaction_ID
Date
Customer_ID
Customer_Segment
Region
Country
Product_Category
Product_Name
Quantity
Unit_Price
Discount_Rate
Total_Sales
Net_Profit
Payment_Method
CSAT_Score
Churn_Risk

# 🎉 Phase 1 Complete

At this stage DataPilot AI can

✅ Connect to Google Drive

✅ Locate the dataset

✅ Load CSV files

✅ Load Excel files

✅ Display the dataset

✅ Inspect dimensions

✅ Display schema

The project foundation is now complete.

# 🧹 Phase 2: Automated Data Quality Engine

Data quality is the foundation of reliable AI systems.

Before performing analytics or machine learning, DataPilot AI evaluates:

- Completeness
- Consistency
- Uniqueness
- Data types
- Potential issues

The output is a Dataset Health Report.

In [ ]:
# ==========================================
# DATASET SUMMARY ENGINE
# ==========================================

def dataset_summary(df):

    summary = {
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Duplicate Rows": df.duplicated().sum(),
        "Missing Cells": df.isnull().sum().sum(),
        "Memory Usage MB": round(
            df.memory_usage(deep=True).sum()/1024**2,
            2
        )
    }

    return pd.DataFrame(
        summary.items(),
        columns=["Metric","Value"]
    )


dataset_summary(df)

            Metric    Value
0             Rows  1003.00
1          Columns    16.00
2   Duplicate Rows     3.00
3    Missing Cells    58.00
4  Memory Usage MB     0.61

## Missing Value Analysis

Missing data can affect:

- Statistical analysis
- Machine learning models
- Business decisions

The AI agent identifies columns requiring attention.

In [ ]:
# ==========================================
# MISSING VALUE DETECTOR
# ==========================================

def missing_value_report(df):

    missing = pd.DataFrame({
        "Column": df.columns,
        "Missing Values": df.isnull().sum(),
        "Missing Percentage":
        (df.isnull().mean()*100).round(2)
    })

    missing = missing[
        missing["Missing Values"] > 0
    ]

    if len(missing)==0:
        return pd.DataFrame(
            {
                "Message":
                ["No missing values detected ✅"]
            }
        )

    return missing.sort_values(
        "Missing Percentage",
        ascending=False
    )


missing_value_report(df)

                Column  Missing Values  Missing Percentage
CSAT_Score  CSAT_Score              58                5.78

## Duplicate Detection

Duplicate records can inflate:

- Revenue
- Customer counts
- Model accuracy

The system detects duplicate transactions.

In [ ]:
# ==========================================
# DUPLICATE ANALYZER
# ==========================================

def duplicate_report(df):

    duplicates = df[df.duplicated()]

    result = {
        "Duplicate Rows":
        len(duplicates),

        "Duplicate Percentage":
        round(
            len(duplicates)/len(df)*100,
            2
        )
    }

    return pd.DataFrame(
        result.items(),
        columns=["Metric","Value"]
    )


duplicate_report(df)

                 Metric  Value
0        Duplicate Rows    3.0
1  Duplicate Percentage    0.3

## Column Type Intelligence

The AI analyst automatically separates:

- Numerical features
- Categorical features
- Date columns

In [ ]:
# ==========================================
# FEATURE TYPE DETECTOR
# ==========================================

def feature_analysis(df):

    numerical = df.select_dtypes(
        include=np.number
    ).columns.tolist()


    categorical = df.select_dtypes(
        include="object"
    ).columns.tolist()


    dates = df.select_dtypes(
        include="datetime"
    ).columns.tolist()


    return {
        "Numerical Columns": numerical,
        "Categorical Columns": categorical,
        "Date Columns": dates
    }


feature_analysis(df)

{'Numerical Columns': ['Quantity',
  'Unit_Price',
  'Discount_Rate',
  'Total_Sales',
  'Net_Profit',
  'CSAT_Score'],
 'Categorical Columns': ['Transaction_ID',
  'Date',
  'Customer_ID',
  'Customer_Segment',
  'Region',
  'Country',
  'Product_Category',
  'Product_Name',
  'Payment_Method',
  'Churn_Risk'],
 'Date Columns': []}

## Data Health Score

DataPilot AI calculates a score out of 100.

Scoring:

Completeness:
40 points

Duplicate Quality:
30 points

Data Type Consistency:
30 points

In [ ]:
# ==========================================
# DATA HEALTH SCORE
# ==========================================


def data_health_score(df):

    total_cells = df.shape[0]*df.shape[1]


    missing_ratio = (
        df.isnull().sum().sum()
        /
        total_cells
    )


    completeness_score = (
        1-missing_ratio
    )*40



    duplicate_ratio = (
        df.duplicated().sum()
        /
        len(df)
    )


    uniqueness_score = (
        1-duplicate_ratio
    )*30



    type_score = 30



    score = (
        completeness_score
        +
        uniqueness_score
        +
        type_score
    )


    return round(score,2)



health = data_health_score(df)

print(
    f"Dataset Health Score: {health}/100"
)

Dataset Health Score: 99.77/100

## AI Cleaning Recommendations

The system explains what should be done.

In [ ]:
# ==========================================
# CLEANING RECOMMENDATION ENGINE
# ==========================================


def generate_recommendations(df):

    recommendations=[]


    missing = df.isnull().sum().sum()

    duplicates = df.duplicated().sum()


    if missing > 0:
        recommendations.append(
            "⚠️ Missing values detected. Apply imputation or removal."
        )
    else:
        recommendations.append(
            "✅ Dataset has no missing values."
        )


    if duplicates > 0:
        recommendations.append(
            "⚠️ Duplicate transactions detected. Review duplicates."
        )
    else:
        recommendations.append(
            "✅ No duplicate records found."
        )


    if len(df.select_dtypes(
        include=np.number).columns)>0:

        recommendations.append(
            "✅ Numerical features detected for statistical analysis."
        )


    recommendations.append(
        "🤖 Dataset is ready for exploratory analysis."
    )


    return recommendations



for item in generate_recommendations(df):
    print(item)

⚠️ Missing values detected. Apply imputation or removal.
⚠️ Duplicate transactions detected. Review duplicates.
✅ Numerical features detected for statistical analysis.
🤖 Dataset is ready for exploratory analysis.

# 🧽 Automated Cleaning Pipeline

The agent creates a cleaned copy.

Operations:

- Remove duplicates
- Standardize column names
- Handle missing values

In [ ]:
# ==========================================
# AUTOMATIC CLEANING
# ==========================================


def clean_dataset(df):

    clean_df = df.copy()


    # standardize columns

    clean_df.columns = (
        clean_df.columns
        .str.lower()
        .str.replace(
            " ",
            "_"
        )
    )


    # remove duplicates

    clean_df = (
        clean_df
        .drop_duplicates()
    )


    # fill numerical missing values

    numerical = clean_df.select_dtypes(
        include=np.number
    ).columns


    for col in numerical:
        clean_df[col] = (
            clean_df[col]
            .fillna(
                clean_df[col].median()
            )
        )


    # fill categorical missing values

    categorical = clean_df.select_dtypes(
        include="object"
    ).columns


    for col in categorical:

        clean_df[col] = (
            clean_df[col]
            .fillna("Unknown")
        )


    return clean_df



clean_df = clean_dataset(df)


clean_df.head()

,transaction_id,date,customer_id,customer_segment,region,country,product_category,product_name,quantity,unit_price,discount_rate,total_sales,net_profit,payment_method,csat_score,churn_risk
0,TXN-10001,2025-01-01,CUST-0239,SMB,Latin America,Brazil,Cloud Services,Serverless Compute Pack,2,430.18,0.00,860.36,507.61,PayPal,5.0,Low
1,TXN-10002,2025-01-01,CUST-0212,Enterprise,North America,USA,Consulting Services,Data Pipeline Audit,14,1566.40,0.25,16447.20,8223.60,Direct Debit,2.0,Medium
2,TXN-10003,2025-01-01,CUST-0212,SMB,Asia Pacific,Japan,Software,Cloud Sync Suite,3,194.03,0.10,523.88,199.07,Credit Card,1.0,Medium
3,TXN-10004,2025-01-02,CUST-0168,Consumer,North America,USA,Cloud Services,Serverless Compute Pack,2,435.67,0.05,827.77,438.72,Direct Debit,3.0,Medium
4,TXN-10005,2025-01-02,CUST-0123,SMB,Europe,Germany,Hardware & Hardware Accessories,IoT Gateway Hub,3,355.95,0.05,1014.46,618.82,PayPal,4.0,Low

# 🎉 Phase 2 Completed

DataPilot AI can now:

✅ Profile datasets  
✅ Detect missing data  
✅ Detect duplicates  
✅ Understand feature types  
✅ Calculate data quality score  
✅ Recommend cleaning actions  
✅ Automatically clean datasets  


Next:

# Phase 3 🚀
## Automated Exploratory Data Analysis + Interactive Dashboard

We will build:

📊 Sales dashboards  
📈 Trend analysis  
🌍 Regional analytics  
👥 Customer segmentation charts  
🔥 Correlation heatmaps  
🎨 Interactive Plotly visualizations

# 📊 Phase 3: Automated Exploratory Data Analysis

Exploratory Data Analysis (EDA) helps discover:

- Patterns
- Trends
- Relationships
- Business opportunities
- Data problems

DataPilot AI automatically explores the dataset and generates insights.

In [ ]:
# ==========================================
# USE CLEAN DATASET
# ==========================================

eda_df = clean_df.copy()

eda_df.head()

,transaction_id,date,customer_id,customer_segment,region,country,product_category,product_name,quantity,unit_price,discount_rate,total_sales,net_profit,payment_method,csat_score,churn_risk
0,TXN-10001,2025-01-01,CUST-0239,SMB,Latin America,Brazil,Cloud Services,Serverless Compute Pack,2,430.18,0.00,860.36,507.61,PayPal,5.0,Low
1,TXN-10002,2025-01-01,CUST-0212,Enterprise,North America,USA,Consulting Services,Data Pipeline Audit,14,1566.40,0.25,16447.20,8223.60,Direct Debit,2.0,Medium
2,TXN-10003,2025-01-01,CUST-0212,SMB,Asia Pacific,Japan,Software,Cloud Sync Suite,3,194.03,0.10,523.88,199.07,Credit Card,1.0,Medium
3,TXN-10004,2025-01-02,CUST-0168,Consumer,North America,USA,Cloud Services,Serverless Compute Pack,2,435.67,0.05,827.77,438.72,Direct Debit,3.0,Medium
4,TXN-10005,2025-01-02,CUST-0123,SMB,Europe,Germany,Hardware & Hardware Accessories,IoT Gateway Hub,3,355.95,0.05,1014.46,618.82,PayPal,4.0,Low

# Dataset Statistical Overview

The AI analyst calculates:

- Mean
- Median
- Standard deviation
- Minimum
- Maximum
- Quartiles

In [ ]:
# ==========================================
# STATISTICAL SUMMARY
# ==========================================

eda_df.describe()

,quantity,unit_price,discount_rate,total_sales,net_profit,csat_score
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000
mean,4.077000,903.889560,0.073350,3192.144900,1584.61885,3.685000
std,3.712796,755.751562,0.074147,4346.349143,2194.43416,1.104987
min,1.000000,142.590000,0.000000,134.780000,50.64000,1.000000
25%,2.000000,308.677500,0.000000,703.950000,355.99500,3.000000
50%,3.000000,570.590000,0.050000,1542.570000,756.86000,4.000000
75%,5.000000,1448.497500,0.100000,3835.362500,1807.55000,4.000000
max,15.000000,2623.640000,0.250000,33189.010000,19289.00000,5.000000

# Categorical Feature Analysis

Understanding business categories:

- Regions
- Products
- Customers
- Payment methods

In [ ]:
# ==========================================
# CATEGORICAL SUMMARY
# ==========================================

categorical_columns = (
    eda_df
    .select_dtypes(include="object")
    .columns
)


for col in categorical_columns:

    print("\n======================")
    print(col)

    print(
        eda_df[col]
        .value_counts()
        .head(10)
    )

======================
transaction_id
transaction_id
TXN-11000    1
TXN-10001    1
TXN-10002    1
TXN-10003    1
TXN-10004    1
TXN-10005    1
TXN-10006    1
TXN-10007    1
TXN-10984    1
TXN-10983    1
Name: count, dtype: int64

======================
date
date
2025-05-16    11
2025-07-14    10
2025-05-23     9
2025-08-05     8
2025-02-05     8
2025-10-11     7
2025-04-23     7
2025-10-29     6
2025-10-04     6
2025-11-02     6
Name: count, dtype: int64

======================
customer_id
customer_id
CUST-0184    14
CUST-0149    13
CUST-0227    13
CUST-0228    12
CUST-0199    12
CUST-0216    12
CUST-0205    11
CUST-0189    11
CUST-0113    11
CUST-0218    11
Name: count, dtype: int64

======================
customer_segment
customer_segment
SMB           440
Consumer      314
Enterprise    246
Name: count, dtype: int64

======================
region
region
North America    395
Europe           314
Asia Pacific     201
Latin America     90
Name: count, dtype: int64

======================
country
country
Canada       199
USA          196
Germany      111
France       102
UK           101
Singapore     77
Australia     73
Japan         51
Brazil        47
Mexico        43
Name: count, dtype: int64

======================
product_category
product_category
Consulting Services                272
Hardware & Hardware Accessories    256
Software                           252
Cloud Services                     220
Name: count, dtype: int64

======================
product_name
product_name
Data Pipeline Audit        144
Custom AI Integration      128
Smart Sensor Node           91
AI Model Hosting            86
DataPilot Pro License       86
Cloud Sync Suite            85
IoT Gateway Hub             84
Security Shield AI          81
Edge AI Accelerator         81
Serverless Compute Pack     73
Name: count, dtype: int64

======================
payment_method
payment_method
PayPal           260
Direct Debit     255
Credit Card      249
Wire Transfer    236
Name: count, dtype: int64

======================
churn_risk
churn_risk
Low       679
Medium    192
High      129
Name: count, dtype: int64

The sales dataset contains business metrics.

DataPilot AI automatically analyses:

- Revenue
- Profit
- Customers
- Products
- Regions

In [ ]:
# ==========================================
# BUSINESS KPI CALCULATOR
# ==========================================


def business_kpis(df):

    kpis = {}

    if "Total_Sales" in df.columns:

        kpis["Total Sales"] = (
            df["Total_Sales"]
            .sum()
        )


    if "Net_Profit" in df.columns:

        kpis["Total Profit"] = (
            df["Net_Profit"]
            .sum()
        )


    if "Customer_ID" in df.columns:

        kpis["Customers"] = (
            df["Customer_ID"]
            .nunique()
        )


    if "Quantity" in df.columns:

        kpis["Units Sold"] = (
            df["Quantity"]
            .sum()
        )


    return pd.DataFrame(
        kpis.items(),
        columns=[
            "Metric",
            "Value"
        ]
    )


business_kpis(eda_df)

Empty DataFrame
Columns: [Metric, Value]
Index: []

Time-based analysis helps discover:

- Growth patterns
- Seasonal behaviour
- Revenue trends

In [ ]:
# ==========================================
# DATE PROCESSING
# ==========================================


if "date" in eda_df.columns:

    eda_df["date"] = pd.to_datetime(
        eda_df["date"]
    )


eda_df.head()

,transaction_id,date,customer_id,customer_segment,region,country,product_category,product_name,quantity,unit_price,discount_rate,total_sales,net_profit,payment_method,csat_score,churn_risk
0,TXN-10001,2025-01-01,CUST-0239,SMB,Latin America,Brazil,Cloud Services,Serverless Compute Pack,2,430.18,0.00,860.36,507.61,PayPal,5.0,Low
1,TXN-10002,2025-01-01,CUST-0212,Enterprise,North America,USA,Consulting Services,Data Pipeline Audit,14,1566.40,0.25,16447.20,8223.60,Direct Debit,2.0,Medium
2,TXN-10003,2025-01-01,CUST-0212,SMB,Asia Pacific,Japan,Software,Cloud Sync Suite,3,194.03,0.10,523.88,199.07,Credit Card,1.0,Medium
3,TXN-10004,2025-01-02,CUST-0168,Consumer,North America,USA,Cloud Services,Serverless Compute Pack,2,435.67,0.05,827.77,438.72,Direct Debit,3.0,Medium
4,TXN-10005,2025-01-02,CUST-0123,SMB,Europe,Germany,Hardware & Hardware Accessories,IoT Gateway Hub,3,355.95,0.05,1014.46,618.82,PayPal,4.0,Low

In [ ]:
monthly_sales = (
    eda_df
    .groupby(
        eda_df["date"]
        .dt.to_period("M")
        .astype(str)
    )["total_sales"]
    .sum()
    .reset_index()
)


monthly_sales.columns = [
    "Month",
    "Sales"
]


monthly_sales

      Month      Sales
0   2025-01  290547.65
1   2025-02  348117.11
2   2025-03  250311.74
3   2025-04  225062.85
4   2025-05  321453.34
5   2025-06  207880.07
6   2025-07  258589.71
7   2025-08  255315.45
8   2025-09  189162.60
9   2025-10  300977.94
10  2025-11  310214.42
11  2025-12  234512.02

In [ ]:
# ==========================================
# SALES TREND CHART
# ==========================================


fig = px.line(
    monthly_sales,
    x="Month",
    y="Sales",
    markers=True,
    title="Monthly Sales Trend"
)


fig.show()

#Regional Analytics

Find which locations generate the most revenue.

In [ ]:
# ==========================================
# SALES BY REGION
# ==========================================


region_sales = (
    eda_df
    .groupby("region")
    ["total_sales"]
    .sum()
    .reset_index()
    .sort_values(
        "total_sales",
        ascending=False
    )
)


region_sales

          region  total_sales
3  North America   1368491.55
1         Europe    968142.13
0   Asia Pacific    561512.64
2  Latin America    293998.58

In [ ]:
fig = px.bar(
    region_sales,
    x="region",
    y="total_sales",
    title="Revenue By Region"
)

fig.show()

#🛒Product Performance Analysis
Identify:

- Best products
- Weak products
- Revenue contributors

In [ ]:
# ==========================================
# TOP PRODUCTS
# ==========================================


top_products = (
    eda_df
    .groupby("product_name")
    ["total_sales"]
    .sum()
    .reset_index()
    .sort_values(
        "total_sales",
        ascending=False
    )
    .head(10)
)


top_products

               product_name  total_sales
2     Custom AI Integration   1187456.38
3       Data Pipeline Audit    766893.00
0          AI Model Hosting    325662.57
4     DataPilot Pro License    166834.66
5       Edge AI Accelerator    166756.60
7      Managed Database Hub    146615.63
9   Serverless Compute Pack    116536.30
6           IoT Gateway Hub    104932.19
8        Security Shield AI     89795.32
10        Smart Sensor Node     60869.43

In [ ]:

fig = px.bar(
    top_products,
    x="total_sales",
    y="product_name",
    orientation="h",
    title="Top 10 Products"
)


fig.show()

#👥Customer Segment Analysis
Analyse customer groups and behaviour.

In [ ]:
# ==========================================
# CUSTOMER SEGMENTS
# ==========================================


segment_analysis = (
    eda_df
    .groupby(
        "customer_segment"
    )
    ["total_sales"]
    .sum()
    .reset_index()
)


segment_analysis

  customer_segment  total_sales
0         Consumer    404734.38
1       Enterprise   1642644.33
2              SMB   1144766.19

In [ ]:
fig = px.pie(
    segment_analysis,
    names="customer_segment",
    values="total_sales",
    title="Sales Distribution By Customer Segment"
)


fig.show()

#🔥 Correlation Intelligence
Correlation helps identify:

- Relationships between variables
- Important numerical features
- Potential ML predictors

In [ ]:
# ==========================================
# CORRELATION MATRIX
# ==========================================


numeric_df = (
    eda_df
    .select_dtypes(
        include=np.number
    )
)


corr = numeric_df.corr()


corr

,quantity,unit_price,discount_rate,total_sales,net_profit,csat_score
quantity,1.000000,-0.023584,0.692873,0.561299,0.537400,0.005430
unit_price,-0.023584,1.000000,-0.006587,0.634023,0.628512,0.012099
discount_rate,0.692873,-0.006587,1.000000,0.361915,0.341131,-0.000547
total_sales,0.561299,0.634023,0.361915,1.000000,0.976673,-0.023332
net_profit,0.537400,0.628512,0.341131,0.976673,1.000000,-0.022455
csat_score,0.005430,0.012099,-0.000547,-0.023332,-0.022455,1.000000

In [ ]:
fig = px.imshow(
    corr,
    text_auto=True,
    title="Feature Correlation Heatmap"
)


fig.show()

🤖 Automatic EDA Insight Generator
The system summarizes major findings automatically.

In [ ]:
# ==========================================
# BASIC INSIGHT ENGINE
# ==========================================


def generate_eda_insights(df):

    insights=[]


    if "Total_Sales" in df.columns:

        best_region = (
            df.groupby("Region")
            ["Total_Sales"]
            .sum()
            .idxmax()
        )

        insights.append(
            f"🌍 Highest revenue region: {best_region}"
        )


    if "Product_Name" in df.columns:

        best_product = (
            df.groupby("Product_Name")
            ["Total_Sales"]
            .sum()
            .idxmax()
        )

        insights.append(
            f"🏆 Best selling product: {best_product}"
        )


    if "Customer_Segment" in df.columns:

        best_segment = (
            df.groupby(
                "Customer_Segment"
            )
            ["Total_Sales"]
            .sum()
            .idxmax()
        )

        insights.append(
            f"👥 Highest value segment: {best_segment}"
        )


    return insights



for insight in generate_eda_insights(eda_df):
    print(insight)

# 🧠 Phase 4: AI Data Analyst Agent

A modern data analyst does not only create charts.

They answer business questions.

DataPilot AI combines:

- Natural Language Processing
- Data Analysis
- Automated Reasoning
- Business Intelligence

to create an AI analyst assistant.

In [ ]:
!pip install -q langchain langchain-community langchain-experimental

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.2/211.2 kB 4.9 MB/s eta 0:00:00

#Agent Architecture
User Question

        ↓

Natural Language Understanding

        ↓

Dataset Interpreter

        ↓

Python Data Analysis Engine

        ↓

Business Answer

In [ ]:
# ==========================================
# PREPARE DATA FOR AI ANALYST
# ==========================================

agent_df = clean_df.copy()

agent_df.head()

,transaction_id,date,customer_id,customer_segment,region,country,product_category,product_name,quantity,unit_price,discount_rate,total_sales,net_profit,payment_method,csat_score,churn_risk
0,TXN-10001,2025-01-01,CUST-0239,SMB,Latin America,Brazil,Cloud Services,Serverless Compute Pack,2,430.18,0.00,860.36,507.61,PayPal,5.0,Low
1,TXN-10002,2025-01-01,CUST-0212,Enterprise,North America,USA,Consulting Services,Data Pipeline Audit,14,1566.40,0.25,16447.20,8223.60,Direct Debit,2.0,Medium
2,TXN-10003,2025-01-01,CUST-0212,SMB,Asia Pacific,Japan,Software,Cloud Sync Suite,3,194.03,0.10,523.88,199.07,Credit Card,1.0,Medium
3,TXN-10004,2025-01-02,CUST-0168,Consumer,North America,USA,Cloud Services,Serverless Compute Pack,2,435.67,0.05,827.77,438.72,Direct Debit,3.0,Medium
4,TXN-10005,2025-01-02,CUST-0123,SMB,Europe,Germany,Hardware & Hardware Accessories,IoT Gateway Hub,3,355.95,0.05,1014.46,618.82,PayPal,4.0,Low

#Create Dataset Context
The AI needs to understand:
Column names
Meaning of variables
Available metrics

In [ ]:
# ==========================================
# DATASET CONTEXT GENERATOR
# ==========================================

def create_dataset_context(df):

    context = f"""
    Dataset Information:

    Rows:
    {df.shape[0]}

    Columns:
    {list(df.columns)}

    Numerical Columns:
    {list(df.select_dtypes(include=np.number).columns)}

    Categorical Columns:
    {list(df.select_dtypes(include='object').columns)}
    """

    return context


dataset_context = create_dataset_context(agent_df)

print(dataset_context)

    Dataset Information:

    Rows:
    1000

    Columns:
    ['transaction_id', 'date', 'customer_id', 'customer_segment', 'region', 'country', 'product_category', 'product_name', 'quantity', 'unit_price', 'discount_rate', 'total_sales', 'net_profit', 'payment_method', 'csat_score', 'churn_risk']

    Numerical Columns:
    ['quantity', 'unit_price', 'discount_rate', 'total_sales', 'net_profit', 'csat_score']

    Categorical Columns:
    ['transaction_id', 'date', 'customer_id', 'customer_segment', 'region', 'country', 'product_category', 'product_name', 'payment_method', 'churn_risk']

#Rule-Based Intelligence Layer
Before using expensive LLMs, good AI systems use deterministic logic.

This gives:

Faster responses

Lower cost

More reliable calculations

In [ ]:

# ==========================================
# ANALYTICAL QUESTION ENGINE
# ==========================================


def data_question_agent(question, df):

    question = question.lower()


    # Highest sales region

    if "highest sales region" in question or "best region" in question:

        result = (
            df.groupby("region")
            ["total_sales"]
            .sum()
            .sort_values(
                ascending=False
            )
            .head(1)
        )

        return (
            f"🌍 The highest sales region is "
            f"{result.index[0]} "
            f"with total sales of "
            f"{result.values[0]:,.2f}"
        )



    # Best product

    elif "best product" in question or "top product" in question:

        result = (
            df.groupby("product_name")
            ["total_sales"]
            .sum()
            .sort_values(
                ascending=False
            )
            .head(1)
        )

        return (
            f"🏆 The best performing product is "
            f"{result.index[0]} "
            f"with sales of "
            f"{result.values[0]:,.2f}"
        )



    # Average satisfaction

    elif "satisfaction" in question or "csat" in question:

        score = (
            df["csat_score"]
            .mean()
        )

        return (
            f"😊 Average customer satisfaction score is "
            f"{score:.2f}"
        )



    # Churn analysis

    elif "churn" in question:

        churn = (
            df["churn_risk"]
            .value_counts()
        )

        return (
            f"⚠️ Churn Risk Distribution:\n\n{churn}"
        )



    # Profit

    elif "profit" in question:

        profit = (
            df["net_profit"]
            .sum()
        )

        return (
            f"💰 Total net profit is "
            f"{profit:,.2f}"
        )


    else:

        return (
            "🤖 I understand your question, "
            "but this analysis is not yet supported. "
            "Try asking about sales, profit, products, "
            "regions, customers, or churn."
        )

#Test The Agent

In [ ]:
questions = [

    "Which region has the highest sales?",

    "What is the best product?",

    "What is the average customer satisfaction?",

    "Show churn analysis",

    "What is total profit?"

]


for q in questions:

    print("\nQUESTION:")
    print(q)

    print("\nANSWER:")
    print(
        data_question_agent(
            q,
            agent_df
        )
    )

    print("-"*50)

QUESTION:
Which region has the highest sales?

ANSWER:
🤖 I understand your question, but this analysis is not yet supported. Try asking about sales, profit, products, regions, customers, or churn.
--------------------------------------------------

QUESTION:
What is the best product?

ANSWER:
🏆 The best performing product is Custom AI Integration with sales of 1,187,456.38
--------------------------------------------------

QUESTION:
What is the average customer satisfaction?

ANSWER:
😊 Average customer satisfaction score is 3.69
--------------------------------------------------

QUESTION:
Show churn analysis

ANSWER:
⚠️ Churn Risk Distribution:

churn_risk
Low       679
Medium    192
High      129
Name: count, dtype: int64
--------------------------------------------------

QUESTION:
What is total profit?

ANSWER:
💰 Total net profit is 1,584,618.85
--------------------------------------------------

#Adding LLM Capability
Now we prepare DataPilot AI for advanced reasoning.

The next version will allow:

Complex questions

Follow-up questions

Explanations

Automated code generation

Example:

User:

"Why did profits decrease in the North region?"

Agent:

"Profit decreased because discount rates increased while average unit price declined."

In [ ]:
# ==========================================
# MAIN AI ANALYST FUNCTION
# ==========================================


def ask_datapilot(question):

    answer = data_question_agent(
        question,
        agent_df
    )

    return answer

#Create Simple Chat Interface
We use Gradio because it will later deploy directly to Hugging Face Spaces.

In [ ]:
# ==========================================
# GRADIO AI ANALYST DEMO
# ==========================================


demo = gr.Interface(

    fn=ask_datapilot,

    inputs=gr.Textbox(
        label="Ask DataPilot AI"
    ),

    outputs=gr.Textbox(
        label="AI Analyst Response"
    ),

    title="🤖 DataPilot AI Analyst",

    description=
    "Ask questions about your sales dataset."
)


demo.launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://7239ec2deb9607fa7e.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

#🎉 Phase 4 Completed
DataPilot AI now has:

✅ Natural language questions

✅ Automated business analysis
✅ Dataset reasoning layer
✅ AI analyst interface
✅ Gradio prototype

# 📄 Phase 5: AI Business Intelligence Report Generator

DataPilot AI transforms raw analytics into actionable decisions.

The system automatically generates:

- Executive summaries
- Revenue insights
- Customer insights
- Product insights
- Risk detection
- Recommendations

Output:
Professional business intelligence report.

In [ ]:
# ==========================================
# REPORT GENERATION LIBRARIES
# ==========================================

!pip install -q fpdf
from datetime import datetime
from fpdf import FPDF
import textwrap

  Preparing metadata (setup.py) ... done
  Building wheel for fpdf (setup.py) ... done

#Build Insight Engine
The AI will automatically discover:
Best region
Best product
Profit performance
Customer behaviour
Churn risk

In [ ]:
# ==========================================
# ADVANCED INSIGHT ENGINE
# ==========================================


def generate_business_insights(df):

    insights = []


    # Revenue leader

    if "Region" in df.columns:

        region = (
            df.groupby("region")
            ["total_sales"]
            .sum()
            .idxmax()
        )

        sales = (
            df.groupby("region")
            ["total_sales"]
            .sum()
            .max()
        )

        insights.append(
            f"🌍 {region} is the strongest region, generating sales of {sales:,.2f}."
        )


    # Product leader

    if "Product_Name" in df.columns:

        product = (
            df.groupby("product_name")
            ["total_sales"]
            .sum()
            .idxmax()
        )

        insights.append(
            f"🏆 {product} is the highest performing product."
        )


    # Profit

    if "Net_Profit" in df.columns:

        profit = df["net_profit"].sum()

        insights.append(
            f"💰 Total net profit generated is {profit:,.2f}."
        )


    # Customer satisfaction

    if "CSAT_Score" in df.columns:

        csat = df["csat_score"].mean()

        insights.append(
            f"😊 Average customer satisfaction score is {csat:.2f}/5."
        )


    # Churn

    if "Churn_Risk" in df.columns:

        churn = (
            df["churn_risk"]
            .value_counts()
            .idxmax()
        )

        insights.append(
            f"⚠️ Most common churn category is {churn}."
        )


    return insights



insights = generate_business_insights(eda_df)


for i in insights:
    print(i)

#Executive Summary Generator
The AI creates a management-level summary.

Example:

"The company generated strong revenue performance.
Region X was the highest contributor.
Customer satisfaction remains positive.
Attention should be given to churn risk."

In [ ]:
# ==========================================
# EXECUTIVE SUMMARY GENERATOR
# ==========================================


def create_executive_summary(df):

    total_sales = df["total_sales"].sum()

    total_profit = df["net_profit"].sum()

    customers = df["customer_id"].nunique()


    summary = f"""
EXECUTIVE SUMMARY

DataPilot AI analysed the sales dataset.

The dataset contains:

- {len(df):,} transactions
- {customers:,} unique customers

Business performance:

- Total Revenue:
  {total_sales:,.2f}

- Total Profit:
  {total_profit:,.2f}

The analysis identified important revenue drivers,
customer behaviour patterns and improvement opportunities.

"""

    return summary



summary = create_executive_summary(eda_df)

print(summary)

EXECUTIVE SUMMARY

DataPilot AI analysed the sales dataset.

The dataset contains:

- 1,000 transactions
- 151 unique customers

Business performance:

- Total Revenue:
  3,192,144.90

- Total Profit:
  1,584,618.85

The analysis identified important revenue drivers,
customer behaviour patterns and improvement opportunities.

#Recommendation Engine
The AI now moves from:
"What happened?"
to:
"What should we do?"

In [ ]:
# ==========================================
# BUSINESS RECOMMENDATIONS
# ==========================================


def generate_recommendations(df):

    recommendations=[]


    avg_discount = (
        df["discount_rate"]
        .mean()
    )


    if avg_discount > 0.15:

        recommendations.append(
            "Reduce excessive discounts to protect profit margins."
        )

    else:

        recommendations.append(
            "Discount strategy appears controlled."
        )



    if "churn_risk" in df.columns:

        high_churn = (
            df["churn_risk"]
            .value_counts()
            .idxmax()
        )


        recommendations.append(
            f"Develop retention campaigns for {high_churn} risk customers."
        )



    recommendations.append(
        "Focus marketing investment on top-performing regions and products."
    )


    return recommendations



recommendations = generate_recommendations(eda_df)


for r in recommendations:
    print("➡️",r)

➡️ Discount strategy appears controlled.
➡️ Develop retention campaigns for Low risk customers.
➡️ Focus marketing investment on top-performing regions and products.

#PDF Report Generator
Now DataPilot AI creates a downloadable business report.

In [ ]:
# ==========================================
# PDF REPORT CREATOR
# ==========================================


def create_pdf_report(
    filename="DataPilot_AI_Report.pdf"
):

    pdf = FPDF()

    pdf.add_page()

    pdf.set_font(
        "Arial",
        size=12
    )


    content = summary + "\n\n"


    content += "KEY INSIGHTS\n\n"

    for item in insights:

        content += item + "\n"


    content += "\n\nRECOMMENDATIONS\n\n"


    for item in recommendations:

        content += "- " + item + "\n"



    for line in content.split("\n"):

        pdf.multi_cell(
            0,
            8,
            line
        )


    pdf.output(filename)


    return filename



report_file = create_pdf_report()


report_file

'DataPilot_AI_Report.pdf'

#Test Generated Report
Open the generated PDF.

Verify:

✅ Executive summary  
✅ Business metrics  
✅ Insights  
✅ Recommendations

In [ ]:
from google.colab import files

files.download(
    "DataPilot_AI_Report.pdf"
)

#Add Report Function To AI Agent
Now the chatbot can create reports.

In [ ]:
# ==========================================
# COMPLETE BUSINESS ANALYST FUNCTION
# ==========================================


def datapilot_report():

    return {
        "Summary": summary,

        "Insights": insights,

        "Recommendations": recommendations,

        "Report":
        "DataPilot_AI_Report.pdf"
    }


datapilot_report()

{'Summary': '\nEXECUTIVE SUMMARY\n\nDataPilot AI analysed the sales dataset.\n\nThe dataset contains:\n\n- 1,000 transactions\n- 151 unique customers\n\nBusiness performance:\n\n- Total Revenue:\n  3,192,144.90\n\n- Total Profit:\n  1,584,618.85\n\nThe analysis identified important revenue drivers,\ncustomer behaviour patterns and improvement opportunities.\n\n',
 'Insights': [],
 'Recommendations': ['Discount strategy appears controlled.',
  'Develop retention campaigns for Low risk customers.',
  'Focus marketing investment on top-performing regions and products.'],
 'Report': 'DataPilot_AI_Report.pdf'}

# 🚀 DataPilot AI Application

## Your Intelligent Data Scientist

Capabilities:

📂 Upload data  
🧹 Data quality analysis  
📊 Automated dashboards  
🤖 Ask questions about data  
📄 Generate business reports  

Built with:

Python + Gradio + Machine Learning

In [ ]:
!pip install -q --upgrade gradio

#Application State
The app needs to remember the uploaded dataset.

In [ ]:
# ==========================================
# GLOBAL DATA STORAGE
# ==========================================

APP_DATA = {
    "raw": None,
    "clean": None
}

#Upload Function
The user uploads CSV/Excel.

The system automatically:

Loads data

Cleans data

Prepares analysis

In [ ]:
# ==========================================
# DATA UPLOAD FUNCTION
# ==========================================


def upload_data(file):

    global APP_DATA


    path = file.name


    if path.endswith(".csv"):

        df = pd.read_csv(path)

    elif path.endswith(".xlsx"):

        df = pd.read_excel(path)

    else:

        return "Unsupported file format"



    APP_DATA["raw"] = df


    APP_DATA["clean"] = clean_dataset(df)



    message = f"""
✅ Dataset Loaded Successfully

Rows:
{df.shape[0]}

Columns:
{df.shape[1]}

Health Score:
{data_health_score(df)}/100
"""


    return message

#Dataset Preview

In [ ]:
def preview_data():

    if APP_DATA["clean"] is None:

        return pd.DataFrame(
            {"Message":["Upload dataset first"]}
        )


    return APP_DATA["clean"].head(20)

Automated Dashboard Generator

In [ ]:
# ==========================================
# DASHBOARD CREATOR
# ==========================================


def create_dashboard():

    df = APP_DATA["clean"]


    if df is None:

        return None,None,None



    # Revenue by region

    region = (
        df.groupby("region")
        ["total_sales"]
        .sum()
        .reset_index()
    )


    fig1 = px.bar(
        region,
        x="region",
        y="total_sales",
        title="Revenue By Region"
    )



    # Products

    products = (
        df.groupby("product_name")
        ["total_sales"]
        .sum()
        .sort_values(
            ascending=False
        )
        .head(10)
        .reset_index()
    )


    fig2 = px.bar(
        products,
        x="total_sales",
        y="product_name",
        orientation="h",
        title="Top Products"
    )



    # Customer segments

    segments = (
        df.groupby("customer_segment")
        ["total_sales"]
        .sum()
        .reset_index()
    )


    fig3 = px.pie(
        segments,
        names="customer_segment",
        values="total_sales",
        title="Customer Segments"
    )


    return fig1,fig2,fig3

#AI Analyst Chat Function

In [ ]:
# ==========================================
# CHAT FUNCTION
# ==========================================


def chat_with_data(question):

    if APP_DATA["clean"] is None:

        return "Please upload a dataset first."


    return data_question_agent(
        question,
        APP_DATA["clean"]
    )

#Report Button Function

In [ ]:
def generate_report():

    if APP_DATA["clean"] is None:

        return "Upload dataset first"


    file = create_pdf_report()

    return file

#Build The Complete Interface
This creates the final product UI.

In [ ]:
# ==========================================
# DATAPILOT AI APP
# ==========================================


with gr.Blocks(
    title="DataPilot AI"
) as app:


    gr.Markdown(
    """
    # 🤖 DataPilot AI

    ### Your Intelligent Data Scientist

    Upload data → Analyse → Ask Questions → Generate Reports
    """
    )



    with gr.Tab("📂 Upload"):

        upload = gr.File(
            label="Upload CSV/XLSX"
        )


        upload_status = gr.Textbox(
            label="System Status"
        )


        upload.upload(
            upload_data,
            inputs=upload,
            outputs=upload_status
        )



    with gr.Tab("👀 Data Preview"):

        preview_btn = gr.Button(
            "Show Dataset"
        )


        preview = gr.Dataframe()


        preview_btn.click(
            preview_data,
            outputs=preview
        )



    with gr.Tab("📊 Dashboard"):


        dashboard_btn = gr.Button(
            "Generate Dashboard"
        )


        chart1 = gr.Plot()

        chart2 = gr.Plot()

        chart3 = gr.Plot()



        dashboard_btn.click(
            create_dashboard,
            outputs=[
                chart1,
                chart2,
                chart3
            ]
        )



    with gr.Tab("🤖 AI Analyst"):


        question = gr.Textbox(
            label="Ask about your data"
        )


        answer = gr.Textbox()


        ask_btn = gr.Button(
            "Ask AI"
        )


        ask_btn.click(
            chat_with_data,
            inputs=question,
            outputs=answer
        )



    with gr.Tab("📄 Report"):


        report_btn = gr.Button(
            "Generate PDF Report"
        )


        report_output = gr.File()



        report_btn.click(
            generate_report,
            outputs=report_output
        )

#Launch Application

In [58]:
app.launch(share=True, debug=True)

Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://905fe1af6330fb3cca.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

Keyboard interruption in main thread... closing server.
Killing tunnel 127.0.0.1:7860 <> https://7239ec2deb9607fa7e.gradio.live
Killing tunnel 127.0.0.1:7861 <> https://905fe1af6330fb3cca.gradio.live

# 🧠 Phase 7: LLM-Powered Data Analyst Agent

DataPilot AI now uses:

- Large Language Models
- Agent tools
- Dataset context
- Natural language reasoning

The goal:

Allow users to ask complex questions without knowing Python or SQL.

In [59]:
!pip install -q \
langchain \
langchain-community \
huggingface_hub \
transformers \
sentence-transformers

#Connect Hugging Face Models
We will use free open-source models.
Recommended:

Mistral

Llama

Zephyr

Qwen

For Hugging Face Spaces, this avoids expensive APIs.

In [60]:
from huggingface_hub import InferenceClient

In [61]:
# =====================================
# HUGGING FACE LLM CONNECTION
# =====================================

HF_TOKEN = "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"


client = InferenceClient(
    token=HF_TOKEN
)

#Dataset Knowledge Base
The AI needs context about the dataset.
We create a dataset profile.

In [62]:
# =====================================
# CREATE DATASET KNOWLEDGE
# =====================================


def create_ai_context(df):

    context = f"""

You You are DataPilot AI,
an expert data scientist.

Dataset:

Rows:
{df.shape[0]}

Columns:

{list(df.columns)}


Numerical Features:

{list(df.select_dtypes(include=np.number).columns)}


Categorical Features:

{list(df.select_dtypes(include='object').columns)}

Sample:

{df.head(3).to_string()}

"""

    return context


APP_DATA["clean"] = clean_df
ai_context = create_ai_context(
    APP_DATA["clean"]
)

print(ai_context)

You You are DataPilot AI,
an expert data scientist.

Dataset:

Rows:
1000

Columns:

['transaction_id', 'date', 'customer_id', 'customer_segment', 'region', 'country', 'product_category', 'product_name', 'quantity', 'unit_price', 'discount_rate', 'total_sales', 'net_profit', 'payment_method', 'csat_score', 'churn_risk']


Numerical Features:

['quantity', 'unit_price', 'discount_rate', 'total_sales', 'net_profit', 'csat_score']


Categorical Features:

['transaction_id', 'date', 'customer_id', 'customer_segment', 'region', 'country', 'product_category', 'product_name', 'payment_method', 'churn_risk']

Sample:

  transaction_id        date customer_id customer_segment         region country     product_category             product_name  quantity  unit_price  discount_rate  total_sales  net_profit payment_method  csat_score churn_risk
0      TXN-10001  2025-01-01   CUST-0239              SMB  Latin America  Brazil       Cloud Services  Serverless Compute Pack         2      430.18           0.00       860.36      507.61         PayPal         5.0        Low
1      TXN-10002  2025-01-01   CUST-0212       Enterprise  North America     USA  Consulting Services      Data Pipeline Audit        14     1566.40           0.25     16447.20     8223.60   Direct Debit         2.0     Medium
2      TXN-10003  2025-01-01   CUST-0212              SMB   Asia Pacific   Japan             Software         Cloud Sync Suite         3      194.03           0.10       523.88      199.07    Credit Card         1.0     Medium

#Create Data Analysis Tools
Agents need tools.

We create:

Statistics tool

Group analysis tool

Correlation tool

In [63]:
# =====================================
# STATISTICS TOOL
# =====================================


def statistics_tool(column):

    df = APP_DATA["clean"]


    if column not in df.columns:

        return "Column does not exist"


    return df[column].describe().to_string()

In [64]:
# =====================================
# GROUP ANALYSIS TOOL
# =====================================


def group_analysis(
    category,
    metric
):

    df = APP_DATA["clean"]


    result = (
        df.groupby(category)[metric]
        .sum()
        .sort_values(
            ascending=False
        )
    )


    return result.head(10).to_string()

In [65]:
# =====================================
# CORRELATION TOOL
# =====================================


def correlation_tool():

    df = APP_DATA["clean"]


    corr = (
        df.select_dtypes(
            include=np.number
        )
        .corr()
    )


    return corr.to_string()

#AI Reasoning Function
Now the LLM receives:

User question

Dataset information

Analytical results
and creates a human answer.

In [66]:
import os
import warnings
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

import gradio as gr

from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer

from ydata_profiling import ProfileReport

warnings.filterwarnings("ignore")

def llm_data_analyst(question):


    df = APP_DATA["clean"]


    if df is None:

        return "Upload dataset first."



    prompt = f"""

{ai_context}


User Question:

{question}


You are a senior data scientist.

Answer the question.

Rules:

- Explain clearly
- Include numbers when possible
- Give business recommendations
- Do not invent data

"""


    response = client.chat_completion(

        model=
        "mistralai/Mistral-7B-Instruct-v0.2",

        messages=[

            {
            "role":"user",
            "content":prompt
            }

        ],

        max_tokens=500

    )


    return (
        response
        .choices[0]
        .message
        .content
    )

#Add Memory Using Embeddings (RAG Preparation)
The next generation of DataPilot AI will remember:

Previous reports

Dataset descriptions

Business documents

In [ ]:
from sentence_transformers import SentenceTransformer


embedding_model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

In [ ]:
# =====================================
# DATASET VECTOR MEMORY
# =====================================


documents = []


for row in APP_DATA["clean"].astype(str).values:

    documents.append(
        " ".join(row)
    )


embeddings = embedding_model.encode(
    documents
)


embeddings.shape

🎉 Phase 7 Completed
DataPilot AI now includes:

✅ LLM reasoning

✅ Dataset understanding

✅ AI-generated explanations

✅ Analytical tools

✅ Embedding foundation

✅ RAG preparation

# 🧠 DataPilot AI Production Agent

The AI analyst now behaves like a real data scientist.

Capabilities:

- Understand uploaded datasets
- Remember conversation context
- Use analytical tools
- Explain findings
- Provide recommendations

In [ ]:
!pip install -q chromadb

#Create Dataset Summary Memory
Instead of sending the whole dataset to the LLM every time, we create a compact memory.

In [ ]:
# =====================================
# DATASET MEMORY SUMMARY
# =====================================


def dataset_memory(df):

    memory = f"""

DATASET PROFILE

Rows:
{df.shape[0]}

Columns:
{list(df.columns)}


Numerical Features:
{list(df.select_dtypes(include=np.number).columns)}


Categorical Features:
{list(df.select_dtypes(include="object").columns)}


Statistics:

{df.describe().to_string()}


Sample Records:

{df.head(5).to_string()}

"""

    return memory

In [ ]:
dataset_memory_text = dataset_memory(
    APP_DATA["clean"]
)

print(dataset_memory_text[:2000])

#Conversation Memory
The AI remembers previous questions.
Example:
User:
Which region has highest sales?
Follow up:
Why?
The agent understands "why" refers to the previous answer.

In [ ]:
# =====================================
# CHAT MEMORY
# =====================================

chat_history = []


def save_chat(
    question,
    answer
):

    chat_history.append(
        {
            "question":question,
            "answer":answer
        }
    )


    return chat_history

#Improved AI Prompt Engineering
Good AI applications depend heavily on prompts.

In [ ]:
# =====================================
# PROFESSIONAL SYSTEM PROMPT
# =====================================


SYSTEM_PROMPT = """

You are DataPilot AI,
an expert senior data scientist.

Your responsibilities:

1. Analyse business datasets
2. Explain insights clearly
3. Support decisions
4. Avoid hallucinating
5. Use only available data

When answering:

- Include metrics
- Explain reasoning
- Give recommendations

"""

print(SYSTEM_PROMPT)

In [ ]:

# =====================================
# FINAL AI AGENT PIPELINE
# =====================================


def datapilot_agent(question):

    if APP_DATA["clean"] is None:

        return "Please upload data first."


    context = dataset_memory(
        APP_DATA["clean"]
    )


    enhanced_prompt = f"""

{SYSTEM_PROMPT}


Dataset Context:

{context}


User Question:

{question}

"""


    # Placeholder response
    # Hugging Face model will be connected during deployment


    answer = data_question_agent(
        question,
        APP_DATA["clean"]
    )


    save_chat(
        question,
        answer
    )


    return answer

In [ ]:
test_questions = [

"Which region has the highest sales?",

"Which product performs best?",

"Give me recommendations to improve profit."

]


for q in test_questions:

    print("\nUSER:")
    print(q)

    print("\nDATAPILOT AI:")

    print(
        datapilot_agent(q)
    )

    print("-"*60)

# 🚀 Preparing DataPilot AI For Deployment

The notebook has been converted into a production application.

The deployment version contains:

- Gradio interface
- Data analysis engine
- AI analyst
- Report generation
- Dataset processing

In [ ]:
import os

PROJECT_NAME = "DataPilot-AI-Agent"

folders = [
    PROJECT_NAME,
    f"{PROJECT_NAME}/sample_data",
    f"{PROJECT_NAME}/assets",
    f"{PROJECT_NAME}/reports"
]


for folder in folders:
    os.makedirs(
        folder,
        exist_ok=True
    )


print("Deployment structure created")

In [ ]:
clean_df.to_csv(
    f"{PROJECT_NAME}/sample_data/datapilot_sample_sales_analytics.csv",
    index=False
)

print("Dataset saved")

In [ ]:
%%writefile DataPilot-AI-Agent/app.py

import gradio as gr
import pandas as pd
import numpy as np
import plotly.express as px
from fpdf import FPDF


DATA = {
    "raw": None,
    "clean": None
}


def clean_dataset(df):

    df = df.copy()

    df.columns = (
        df.columns
        .str.lower()
        .str.replace(" ","_")
    )


    df = df.drop_duplicates()


    for col in df.select_dtypes(
        include=np.number
    ):

        df[col] = df[col].fillna(
            df[col].median()
        )


    for col in df.select_dtypes(
        include="object"
    ):

        df[col] = df[col].fillna(
            "Unknown"
        )


    return df



def upload_data(file):

    if file.name.endswith(".csv"):

        df = pd.read_csv(
            file.name
        )

    else:

        df = pd.read_excel(
            file.name
        )


    DATA["raw"] = df

    DATA["clean"] = clean_dataset(df)


    return f"""
Dataset loaded successfully

Rows:
{df.shape[0]}

Columns:
{df.shape[1]}
"""



def preview():

    return DATA["clean"].head(20)



def dashboard():

    df = DATA["clean"]


    region = (
        df.groupby("region")
        ["total_sales"]
        .sum()
        .reset_index()
    )


    fig1 = px.bar(
        region,
        x="region",
        y="total_sales",
        title="Sales By Region"
    )


    product = (
        df.groupby("product_name")
        ["total_sales"]
        .sum()
        .sort_values(
            ascending=False
        )
        .head(10)
        .reset_index()
    )


    fig2 = px.bar(
        product,
        x="total_sales",
        y="product_name",
        orientation="h",
        title="Top Products"
    )


    return fig1,fig2



def analyst(question):

    df = DATA["clean"]


    q = question.lower()


    if "profit" in q:

        return (
            f"Total profit is "
            f"{df['net_profit'].sum():,.2f}"
        )


    if "region" in q:

        result = (
            df.groupby("region")
            ["total_sales"]
            .sum()
            .idxmax()
        )


        return (
            f"Highest sales region: {result}"
        )


    if "product" in q:

        result = (
            df.groupby("product_name")
            ["total_sales"]
            .sum()
            .idxmax()
        )


        return (
            f"Best product: {result}"
        )


    return (
        "Ask about sales, profit, regions or products."
    )



with gr.Blocks(
    title="DataPilot AI"
) as demo:


    gr.Markdown(
    """
    # 🤖 DataPilot AI

    Your Intelligent Data Scientist
    """
    )


    with gr.Tab("Upload"):

        file = gr.File()

        status = gr.Textbox()


        file.upload(
            upload_data,
            file,
            status
        )



    with gr.Tab("Preview"):

        button = gr.Button(
            "Show Data"
        )

        table = gr.Dataframe()


        button.click(
            preview,
            outputs=table
        )



    with gr.Tab("Dashboard"):

        button = gr.Button(
            "Generate Dashboard"
        )

        chart1 = gr.Plot()

        chart2 = gr.Plot()


        button.click(
            dashboard,
            outputs=[
                chart1,
                chart2
            ]
        )



    with gr.Tab("AI Analyst"):

        question = gr.Textbox()

        answer = gr.Textbox()


        ask = gr.Button(
            "Ask DataPilot"
        )


        ask.click(
            analyst,
            question,
            answer
        )



demo.launch()

In [ ]:
%%writefile DataPilot-AI-Agent/requirements.txt

gradio
pandas
numpy
plotly
openpyxl
fpdf2
scikit-learn

In [ ]:
%%writefile DataPilot-AI-Agent/README.md

# 🤖 DataPilot AI

An AI-powered data analyst agent.

## Features

- CSV/Excel analysis
- Data cleaning
- Automated EDA
- Interactive dashboards
- AI data questions
- Business insights

## Tech Stack

Python
Gradio
Pandas
Plotly
Machine Learning

## Deployment

Hosted on Hugging Face Spaces.

In [ ]:
from google.colab import files

!zip -r DataPilot-AI-Agent.zip DataPilot-AI-Agent

In [ ]:
files.download(
    "DataPilot-AI-Agent.zip"
)